org.gradle.jvmargs = -Xmx6096M
org.gradle.parallel = true
org.gradle.daemon = false

java_version = 17

# Mc stuff
minecraft_version = 1.20.1
minecraft_min_version = 1.20.1
minecraft_max_version = 1.20.2

enabled_platforms = fabric,forge
pack_format_number = 15

# Mod stuff
mod_id = sleep_tight
mod_name = Sleep Tight
mod_version = 1.20-1.2.4
mod_license = Supplementaries Team License v.1.2
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar, Plantkillable
mod_description = Balanced sleep overhaul & hammocks. Don't let bedbugs bite!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/sleep_tight
mod_github = https://github.com/MehVahdJukaar/sleep_tight
mod_credits = MehvahdJukaar, Plantkillable

project_id = 817564
modrinth_id = sleep-tight
release_type = release

# Loaders
parchment_version = 1.20.1:2023.09.03

fabric_loader_version = 0.16.10
fabric_api_version = 0.92.3+1.20.1


forge_version = 1.20.1-47.3.22
neo_version = 47.1.79
neo_version_range = [47.1,)
loader_version_range = [4,)


modmenu_version = 4.0.0
cloth_version = 7.0.72

required_moonlight_version = 1.20-2.14.2
moonlight_version = 1.20-2.14.5
heartstone_version = 1.20-1.3.0
supplementaries_vesion = 1.20-3.1.33

sbl_version = 1.15




