systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
loom.ignoreDependencyLoomVersionValidation = true
loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false


org.gradle.jvmargs = -Xmx6096M
org.gradle.parallel = true
org.gradle.daemon = false

java_version = 21

# Mc stuff
minecraft_version = 1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.21.2

enabled_platforms = fabric,neoforge
pack_format_number = 15

# Mod stuff
mod_id = sleep_tight
mod_name = Sleep Tight
mod_version = 1.21-1.3.7
mod_license = Supplementaries Team License v.1.5
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar, Plantkillable
mod_description = Balanced sleep overhaul & hammocks. Don't let bedbugs bite!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/sleep_tight
mod_github = https://github.com/MehVahdJukaar/sleep_tight
mod_credits = MehvahdJukaar, Plantkillable

cf_project_id = 817564
mr_project_id = sleep-tight
release_type = release

# Loaders
parchment_version = 1.21:2024.07.28

fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1

neo_version = 21.1.206
neo_version_range = [4,)
loader_version_range = [4,)


modmenu_version = 4.0.0
cloth_version = 7.0.72

required_moonlight_version = 1.21-2.23.3
moonlight_version = 1.21-2.23.3
moonlight_min_version = 1.21-2.23.3
heartstone_version = 1.20-1.3.0
supplementaries_vesion = 1.20-3.1.33

sbl_version = 1.15




