architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}



publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.output_directory=${new File(rootProject.buildDir, "docsOut")}")
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.multi_source=true")

    it.options.compilerArgs << "-Xmaxerrs" << "4000"

}


dependencies {

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    modImplementation("net.mehvahdjukaar:moonlight:${project.moonlight_version}")
    modImplementation("net.mehvahdjukaar:heartstone:${project.heartstone_version}")
    modImplementation ("curse.maven:supplementaries-412082:4375776")
    modImplementation("curse.maven:entity-model-features-844662:5722728")
    modImplementation("curse.maven:entity-texture-features-fabric-568563:5000985")

    modCompileOnly("org.violetmoon.quark:Quark-4.0-beta-426")
    modCompileOnly("org.violetmoon.zeta:Zeta-1.0-beta-1")

    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${project.minecraft_version}:${project.sbl_version}"
    modImplementation ("curse.maven:handcrafted-538214:6330030")
    modImplementation ("curse.maven:resourceful-lib-570073:5659871")
    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${project.minecraft_version}:${project.sbl_version}"
}

